- definition: io.k8s.api.core.v1.PodSpec
  field_categories:
  - name: Containers
    fields:
    - containers *half-sensitive*
    - initContainers *half-sensitive*
    - ephemeralContainers *half-sensitive*
    - imagePullSecrets *sensitive*
    - enableServiceLinks
    - os
  - name: Volumes
    fields:
    - volumes
  - name: Scheduling
    fields:
    - nodeSelector
    - nodeName
    - affinity
    - tolerations
    - schedulerName
    - runtimeClassName
    - priorityClassName
    - priority
    - preemptionPolicy
    - topologySpreadConstraints
    - overhead
  - name: Lifecycle *half-sensitive*
    fields:
    - restartPolicy
    - terminationGracePeriodSeconds
    - activeDeadlineSeconds
    - readinessGates
  - name: Hostname and Name resolution
    fields:
    - hostname
    - setHostnameAsFQDN
    - subdomain
    - hostAliases
    - dnsConfig
    - dnsPolicy
  - name: Hosts namespaces
    fields:
    - hostNetwork
    - hostPID
    - hostIPC
    - shareProcessNamespace
  - name: Service account *half-sensitive*
    fields:
    - serviceAccountName
    - automountServiceAccountToken
  - name: Security context *half-sensitive*
    fields:
    - securityContext
  - name: Alpha level
    fields:
    - hostUsers
    - resourceClaims
    - schedulingGates
  - name: Deprecated
    fields:
    - serviceAccount

- definition: io.k8s.api.core.v1.PodSecurityContext *half-sensitive*
  field_categories:
  - fields:
    - runAsUser
    - runAsNonRoot
    - runAsGroup
    - supplementalGroups
    - fsGroup
    - fsGroupChangePolicy
    - seccompProfile
    - seLinuxOptions
    - sysctls
    - windowsOptions

- definition: io.k8s.api.core.v1.Toleration *half-sensitive*
  field_categories:
  - fields:
    - key
    - operator
    - value
    - effect
    - tolerationSeconds

- definition: io.k8s.api.core.v1.PodStatus *non-sensitive*
  field_categories:
  - fields:
    - nominatedNodeName
    - hostIP
    - startTime
    - phase
    - message
    - reason
    - podIP
    - podIPs
    - conditions
    - qosClass
    - initContainerStatuses
    - containerStatuses
    - ephemeralContainerStatuses

- definition: io.k8s.api.core.v1.Container *half-sensitive*
  field_categories:
  - fields:
    - name
  - name: Image
    fields:
    - image
    - imagePullPolicy
  - name: Entrypoint
    fields:
    - command *sensitive*
    - args *sensitive*
    - workingDir
  - name: Ports
    fields:
    - ports
  - name: Environment variables
    fields:
    - env *sensitive*
    - envFrom
  - name: Volumes
    fields:
    - volumeMounts
    - volumeDevices
  - name: Resources
    fields:
    - resources
  - name: Lifecycle *half-sensitive*
    fields:
    - lifecycle
    - terminationMessagePath
    - terminationMessagePolicy
    - livenessProbe
    - readinessProbe
    - startupProbe
  - name: Security Context
    fields:
    - securityContext
  - name: Debugging
    fields:
    - stdin
    - stdinOnce
    - tty

- definition: io.k8s.api.core.v1.Probe *half-sensitive*
  field_categories:
  - fields:
    - exec
    - httpGet
    - tcpSocket
    - initialDelaySeconds
    - terminationGracePeriodSeconds
    - periodSeconds
    - timeoutSeconds
    - failureThreshold
    - successThreshold
    - grpc

- definition: io.k8s.api.core.v1.SecurityContext *half-sensitive*
  field_categories:
  - fields:
    - runAsUser
    - runAsNonRoot
    - runAsGroup
    - readOnlyRootFilesystem
    - procMount
    - privileged
    - allowPrivilegeEscalation
    - capabilities
    - seccompProfile
    - seLinuxOptions
    - windowsOptions

- definition: io.k8s.api.core.v1.ContainerStatus *half-sensitive*
  field_categories:
  - fields:
    - name
    - image
    - imageID
    - containerID
    - state
    - lastState
    - ready
    - restartCount
    - started

- definition: io.k8s.api.core.v1.ContainerStateTerminated *half-sensitive*
  field_categories:
  - fields:
    - containerID
    - exitCode
    - startedAt
    - finishedAt
    - message *sensitive*
    - reason *sensitive*
    - signal

- definition: io.k8s.api.core.v1.EphemeralContainer *half-sensitive*
  field_categories:
  - fields:
    - name
    - targetContainerName
  - name: Image
    fields:
    - image
    - imagePullPolicy
  - name: Entrypoint
    fields:
    - command *sensitive*
    - args *sensitive*
    - workingDir
  - name: Environment variables
    fields:
    - env *sensitive*
    - envFrom
  - name: Volumes
    fields:
    - volumeMounts
    - volumeDevices
  - name: Lifecycle *half-sensitive*
    fields:
    - terminationMessagePath
    - terminationMessagePolicy
  - name: Debugging
    fields:
    - stdin
    - stdinOnce
    - tty
  - name: Security context *half-sensitive*
    fields:
    - securityContext
  - name: Not allowed
    fields:
    - ports
    - resources
    - lifecycle
    - livenessProbe
    - readinessProbe
    - startupProbe

- definition: io.k8s.api.core.v1.ReplicationControllerSpec *half-sensitive*
  field_categories:
  - fields:
    - selector
    - template
    - replicas
    - minReadySeconds

- definition: io.k8s.api.core.v1.ReplicationControllerStatus *half-sensitive*
  field_categories:
  - fields:
    - replicas
    - availableReplicas
    - readyReplicas
    - fullyLabeledReplicas
    - conditions
    - observedGeneration

- definition: io.k8s.api.apps.v1.ReplicaSetSpec *half-sensitive*
  field_categories:
  - fields:
    - selector
    - template
    - replicas
    - minReadySeconds

- definition: io.k8s.api.apps.v1.ReplicaSetStatus *half-sensitive*
  field_categories:
  - fields:
    - replicas
    - availableReplicas
    - readyReplicas
    - fullyLabeledReplicas
    - conditions
    - observedGeneration

- definition: io.k8s.api.apps.v1.DeploymentSpec *half-sensitive*
  field_categories:
  - fields:
    - selector
    - template
    - replicas
    - minReadySeconds
    - strategy
    - revisionHistoryLimit
    - progressDeadlineSeconds
    - paused

- definition: io.k8s.api.apps.v1.DeploymentStatus *half-sensitive*
  field_categories:
  - fields:
    - replicas
    - availableReplicas
    - readyReplicas
    - unavailableReplicas
    - updatedReplicas
    - collisionCount
    - conditions
    - observedGeneration

- definition: io.k8s.api.apps.v1.DeploymentStrategy *half-sensitive*
  field_categories:
  - fields:
    - type
    - rollingUpdate

- definition: io.k8s.api.apps.v1.StatefulSetSpec *half-sensitive*
  field_categories:
  - fields:
    - serviceName
    - selector
    - template
    - replicas
    - updateStrategy
    - podManagementPolicy
    - revisionHistoryLimit
    - volumeClaimTemplates
    - minReadySeconds
    - persistentVolumeClaimRetentionPolicy
    - ordinals

- definition: io.k8s.api.apps.v1.StatefulSetUpdateStrategy *half-sensitive*
  field_categories:
  - fields:
    - type
    - rollingUpdate

- definition: io.k8s.api.apps.v1.StatefulSetStatus *half-sensitive*
  field_categories:
  - fields:
    - replicas
    - readyReplicas
    - currentReplicas
    - updatedReplicas
    - availableReplicas
    - collisionCount
    - conditions
    - currentRevision
    - updateRevision
    - observedGeneration

- definition: io.k8s.api.apps.v1.DaemonSetSpec *half-sensitive*
  field_categories:
  - fields:
    - selector
    - template
    - minReadySeconds
    - updateStrategy
    - revisionHistoryLimit

- definition: io.k8s.api.apps.v1.DaemonSetUpdateStrategy *half-sensitive*
  field_categories:
  - fields:
    - type
    - rollingUpdate

- definition: io.k8s.api.apps.v1.DaemonSetStatus *half-sensitive*
  field_categories:
  - fields:
    - numberReady
    - numberAvailable
    - numberUnavailable
    - numberMisscheduled
    - desiredNumberScheduled
    - currentNumberScheduled
    - updatedNumberScheduled
    - collisionCount
    - conditions
    - observedGeneration

- definition: io.k8s.api.batch.v1.JobSpec *half-sensitive*
  field_categories:
  - name: Replicas
    fields:
    - template
    - parallelism
  - name: Lifecycle *half-sensitive*
    fields:
    - completions
    - completionMode
    - backoffLimit
    - activeDeadlineSeconds
    - ttlSecondsAfterFinished
    - suspend
  - name: Selector
    fields:
    - selector
    - manualSelector
  - name: Alpha level
    fields:
    - podFailurePolicy

- definition: io.k8s.api.batch.v1.JobStatus *half-sensitive*
  field_categories:
  - fields:
    - startTime
    - completionTime
    - active
    - failed
    - succeeded
    - completedIndexes
    - conditions
    - uncountedTerminatedPods
  - name: Beta level
    fields:
    - ready

- definition: io.k8s.api.batch.v1.CronJobSpec *half-sensitive*
  field_categories:
  - fields:
    - jobTemplate
    - schedule
    - timeZone
    - concurrencyPolicy
    - startingDeadlineSeconds
    - suspend
    - successfulJobsHistoryLimit
    - failedJobsHistoryLimit

- definition: io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerSpec *half-sensitive*
  field_categories:
  - fields:
    - maxReplicas
    - scaleTargetRef
    - minReplicas
    - behavior
    - metrics

- definition: io.k8s.api.autoscaling.v2beta2.HPAScalingPolicy *half-sensitive*
  field_categories:
  - fields:
    - type
    - value
    - periodSeconds

- definition: io.k8s.api.autoscaling.v2.HorizontalPodAutoscalerSpec *half-sensitive*
  field_categories:
  - fields:
    - maxReplicas
    - scaleTargetRef
    - minReplicas
    - behavior
    - metrics

- definition: io.k8s.api.autoscaling.v2.HPAScalingPolicy *half-sensitive*
  field_categories:
  - fields:
    - type
    - value
    - periodSeconds

- definition: io.k8s.api.core.v1.ServiceSpec *half-sensitive*
  field_categories:
  - fields:
    - selector
    - ports
    - type
    - ipFamilies
    - ipFamilyPolicy
    - clusterIP
    - clusterIPs
    - externalIPs
    - sessionAffinity
    - loadBalancerIP
    - loadBalancerSourceRanges
    - loadBalancerClass
    - externalName
    - externalTrafficPolicy
    - internalTrafficPolicy
    - healthCheckNodePort
    - publishNotReadyAddresses
    - sessionAffinityConfig
    - allocateLoadBalancerNodePorts

- definition: io.k8s.api.core.v1.ServicePort *half-sensitive*
  field_categories:
  - fields:
    - port
    - targetPort
    - protocol
    - name
    - nodePort
    - appProtocol

- definition: io.k8s.api.core.v1.EndpointSubset *half-sensitive*
  field_categories:
  - fields:
    - addresses
    - notReadyAddresses
    - ports

- definition: io.k8s.api.core.v1.EndpointPort *half-sensitive*
  field_categories:
  - fields:
    - port
    - protocol
    - name
    - appProtocol

- definition: io.k8s.api.discovery.v1.EndpointPort *half-sensitive*
  field_categories:
  - fields:
    - port
    - protocol
    - name
    - appProtocol

- definition: io.k8s.api.core.v1.Volume *half-sensitive*
  field_categories:
  - fields:
    - name
  - name: Exposed Persistent volumes
    fields:
    - persistentVolumeClaim
  - name: Projections
    fields:
    - configMap *sensitive*
    - secret *sensitive*
    - downwardAPI
    - projected
  - name: Local / Temporary Directory
    fields:
    - emptyDir
    - hostPath
  - name: Persistent volumes
    fields:
    - awsElasticBlockStore
    - azureDisk
    - azureFile
    - cephfs
    - cinder
    - csi
    - ephemeral
    - fc
    - flexVolume
    - flocker
    - gcePersistentDisk
    - glusterfs
    - iscsi
    - nfs
    - photonPersistentDisk
    - portworxVolume
    - quobyte
    - rbd
    - scaleIO
    - storageos
    - vsphereVolume
  - name: Deprecated
    fields:
    - gitRepo

- definition: io.k8s.api.core.v1.ConfigMapVolumeSource *half-sensitive*
  field_categories:
  - fields:
    - name
    - optional
    - defaultMode
    - items

- definition: io.k8s.api.core.v1.SecretVolumeSource *half-sensitive*
  field_categories:
  - fields:
    - secretName
    - optional
    - defaultMode
    - items

- definition: io.k8s.api.core.v1.ConfigMapProjection *half-sensitive*
  field_categories:
  - fields:
    - name
    - optional
    - items

- definition: io.k8s.api.core.v1.SecretProjection *half-sensitive*
  field_categories:
  - fields:
    - name
    - optional
    - items

- definition: io.k8s.api.core.v1.ProjectedVolumeSource *half-sensitive*
  field_categories:
  - fields:
    - defaultMode
    - sources

- definition: io.k8s.api.core.v1.PersistentVolumeClaimSpec *half-sensitive*
  field_categories:
  - fields:
    - accessModes
    - selector
    - resources
    - volumeName
    - storageClassName
    - volumeMode
  - name: Beta level
    fields:
    - dataSource
    - dataSourceRef

- definition: io.k8s.api.core.v1.PersistentVolumeSpec *half-sensitive*
  field_categories:
  - fields:
    - accessModes
    - capacity
    - claimRef
    - mountOptions
    - nodeAffinity
    - persistentVolumeReclaimPolicy
    - storageClassName
    - volumeMode
  - name: Local
    fields:
    - hostPath
    - local
  - name: Persistent volumes
    fields:
    - awsElasticBlockStore
    - azureDisk
    - azureFile
    - cephfs
    - cinder
    - csi
    - fc
    - flexVolume
    - flocker
    - gcePersistentDisk
    - glusterfs
    - iscsi
    - nfs
    - photonPersistentDisk
    - portworxVolume
    - quobyte
    - rbd
    - scaleIO
    - storageos
    - vsphereVolume

- definition: io.k8s.api.rbac.v1.PolicyRule *half-sensitive*
  field_categories:
  - fields:
    - apiGroups
    - resources
    - verbs
    - resourceNames
    - nonResourceURLs

- definition: io.k8s.api.networking.v1.NetworkPolicySpec
  field_categories:
  - fields:
    - podSelector
    - policyTypes
    - ingress
    - egress

- definition: io.k8s.api.networking.v1.NetworkPolicyEgressRule
  field_categories:
  - fields:
    - to
    - ports

- definition: io.k8s.api.networking.v1.NetworkPolicyPort
  field_categories:
  - fields:
    - port
    - endPort
    - protocol

- definition: io.k8s.api.policy.v1beta1.PodSecurityPolicySpec
  field_categories:
  - fields:
    - runAsUser
    - runAsGroup
    - fsGroup
    - supplementalGroups
    - seLinux
    - readOnlyRootFilesystem
    - privileged
    - allowPrivilegeEscalation
    - defaultAllowPrivilegeEscalation
    - allowedCSIDrivers
    - allowedCapabilities
    - requiredDropCapabilities
    - defaultAddCapabilities
    - allowedFlexVolumes
    - allowedHostPaths
    - allowedProcMountTypes
    - allowedUnsafeSysctls
    - forbiddenSysctls
    - hostIPC
    - hostNetwork
    - hostPID
    - hostPorts
    - runtimeClass
    - volumes

- definition: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  field_categories:
  - fields:
    - name
    - generateName
    - namespace
    - labels
    - annotations
  - name: System
    fields:
    - finalizers
    - managedFields
    - ownerReferences
  - name: Read-only
    fields:
    - creationTimestamp
    - deletionGracePeriodSeconds
    - deletionTimestamp
    - generation
    - resourceVersion
    - selfLink
    - uid
